---
title: "**Advanced Reproducibility**"
output:
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
css: style.css
editor_options:
  markdown:
    wrap: 72
---


# Activity 0: Set Up

[Slides are located here](https://docs.google.com/presentation/d/1_5FJ6SYA2t1F7BX5-Vvzi2LHEVUmXS4eFvousSqcl9w/edit?usp=sharing) 

### Installing Docker

<input type="checkbox"> Go here to [install Docker Desktop](https://www.docker.com/get-started), following the instructions for your particular operating system.

<input type="checkbox"> If you don't have a Docker account yet, create an account when prompted, or [go here](https://hub.docker.com/).
After you install Docker, start up Docker Desktop by double clicking on the app. It may take some time to start up. 

<input type="checkbox"> Docker Desktop may ask you to log in to your Docker account. 

### Set up sandbox repository for this workshop

<br>

<details> <summary>Click here if you did not attend the first workshop!</summary>

:::explain_block


**NOTE: If you completed these steps for the previous workshop you don't need to do them again!**

<span style="font-size: 250%"> Create your own copy of this repository </span>

<input type="checkbox"> Go to the template repository for this workshop: https://github.com/fhdsl/reproducibility-sandbox  

<input type="checkbox"> Click the green `Use this template` button and then `Create a new repository`. If you don't see this button, you may need to expand your window.  
<input type="checkbox"> On the next screen, create a `Repository name`.   

<input type="checkbox"> Choose `Public`.  

<input type="checkbox"> Scroll to the bottom and click `Create repository`.  

<span style="font-size: 250%">Cloning our repository</span>

<input type="checkbox"> Open up GitHub Desktop on your computer.  

<input type="checkbox"> Go to `File` > `Clone Repository`. 

<input type="checkbox"> Search for your ITN workshop repository name in the tab that says `Github.com`. Click on the name of this repository in this list. You can choose where you'd like it to download on your computer underneath `Local Path`.

<input type="checkbox"> Click the blue `Clone` button.  


:::

</details>



<br>


# Activity 1: Getting familiar with Docker/Podman

### Step 1: Docker pull


<input type="checkbox">Search for the following image in the search box of Docker Desktop: `hudsl/reproducible-r`.

<input type="checkbox"> Click on the `pull` button for this image.


Alternatively you could use commands:

<input type="checkbox"> Open terminal in Docker Desktop. Do so by clicking the lower right corner that has a symbol like this `>_`.

<input type="checkbox"> We need to get the Docker **image** we want to use. We do this by "pulling" it.

Run this command by copy pasting and clicking enter in your terminal:

```
docker pull jhudsl/reproducible-r
```

### Step 2: Check what images you have

<input type="checkbox"> After the last steps complete, we can see what images we have by clicking on the `Images` tab on the left menu in Docker Desktop. We should see `jhudsl/reproducible-r` show up now.

<input type="checkbox">  We can also see what images we have by using the command `docker image ls` in the terminal. 



### Step 3: Run the Docker image to start a container!

<input type="checkbox"> Now if we want to launch the image for use, we can use run button that looks like a triangle to turn the image into a **container**

<input type="checkbox"> Alternatively, we could also use `docker run` as a command in the terminal:

```
docker run jhudsl/reproducible-r
```

<input type="checkbox"> To see what containers we have running we check the `Containers` tab in Docker Desktop.

<input type="checkbox"> Alternatively, we can run the following command in the terminal:

```
docker ps
```

### Step 4: Run a single command

<input type="checkbox"> To use code on the fly interactively from the command line we can click on the container name (if needed) and click on the `Exec` tab in Docker Desktop 


<input type="checkbox"> Alternatively,  we can use the following command in the terminal:

```
docker exec -it <PUT_CONTAINER_ID_HERE> bash
```

We should now see a `#` at the end of the line showing that we can enter commands for the container interactively.


### Step 5: Add our reproducibility-sandbox files 

Our container is separate from our computer so if we want to use a file we have to attach it using a "volume".


If we want to run `run_analysis.sh` there are other ways we could get the file on our container, but one of the best ways is using a `volume`.

A `volume`  is a set of files that are local to our computer that are accessible by the container. 

<input type="checkbox">  In Docker Desktop, we can click on the `Images` tab in the left menu.

<input type="checkbox"> Then click on the play button for our `jhudsl/reproducible-r` image.

<input type="checkbox"> This time click the downward arrow for running options.

<input type="checkbox"> We will add `8787` as the host port.

<input type="checkbox"> Now we can add the file path for our script file on our computer by clicking on the three dot menu button in the box that says `Host path`. Navigate to where you saved your files earlier from the repository.

<input type="checkbox"> For the container path type `/home`.

<input type="checkbox"> Click `Run`.

The container will launch again but this time with your files.


Alternatively, we can do something similar in the terminal.

We can run our Docker container with the volume `-v` option.

We can specify a particular file path on our computer or we can give it `$PWD`.

Then  we can give a `:` and a file path where we'd like the files to be stored on the container. Otherwise it will be stored at the absolute top of the container.

We are also going to add a port specification as well `-p 8787:8787` This will allow us to use RStudio on our container.


<input type="checkbox"> If you are in the directory where you saved the repository files, you can now run:

```
docker run -v $PWD:/home -p 8787:8787 jhudsl/reproducible-r 

```

The reason you need to be in the directory with your files is because `$PWD` is a special environment variable that stores the absolute path of the current working directory. This will enable the next step to call the script file.

Note that if you already did this using the buttons in Docker Desktop you may get an error that the port is already allocated. You can stop your other container (by clicking the trash button near the listed container in your Containers tab) to rerun this from the command line.


### Step 6: Call a script

<input type="checkbox"> Click `Exec` to launch  execute mode.

<input type="checkbox"> Go to the home directory specified to where our files were added by typing the following and pressing enter after:

```
cd /home
```

<input type="checkbox"> Now try to run the script.

```
bash run_analysis.sh

```

Great! Now you should see the script running. You will know because you will see text about what the script is doing.

After a bit you should see the following:

```
Output created: 01-heatmap.nb.html
```

<input type="checkbox"> Alternatively if you have been working in the terminal, we could open a new terminal and use the following:
```
docker exec -it <REPLACE_WITH_CONTAINER_ID> bash /home/run_analysis.sh
```
And this should work!

Similarly after a bit you should see the following in the terminal:

```
Output created: 01-heatmap.nb.html
```

### Step 7: Using RStudio from a container

<input type="checkbox"> Click on the link that says 8787:8787 at the top of your Docker Desktop (in the Container tab) OR go to your internet browser and type in `localhost:8787`.  

<input type="checkbox"> Now type in "rstudio" for your username and then find the password that was set in your Docker logs and copy and past that for your password.
(It will likely be in red).

<input type="checkbox"> Click submit.

Now you can develop code from RStudio from a container that is shareable!

::: {.notice}
Keep in mind you can install packages from here but they will not be saved to the original image after you stop the container. To add software to your image you will need to modify your image which [you can find instructions on how to do this in our full course](https://hutchdatascience.org/Containers_for_Scientists/05-modifying-containers.html).
:::

# Activity 2: Getting familiar with GitHub Actions

## Step 1: Manually initiate a GitHub Action workflow

<input type="checkbox"> Go to your `reproducibility-sandbox` repository online on GitHub.

<input type="checkbox"> Click on the `Actions` tab. 

<input type="checkbox"> On the left side of the screen click on the `Render R Example` action.   

<input type="checkbox"> Click on the `Run workflow` dropdown menu and pick the green `Run workflow` button. You should see a light blue banner on the top that says "Workflow run was successfully requested".   

## Step 2: Take a look at the workflow file

<input type="checkbox"> In your repository go to `.github/workflows/run-r-notebook.yml`.  
<input type="checkbox"> Take a look at this workflow file and try to answer these questions:

1. When will this workflow be run?
2. What will this workflow do when it is run?
3. What is this being run on -- what is the computing environment being used here?  

## Step 3: Take a look at your GitHub Action run!

<input type="checkbox"> Go back to the `Actions` tab. You may need to refresh the page.

<input type="checkbox"> Click on the Workflow run in the center of the page that also says `Render R example`.

<input type="checkbox"> Click on the small box that says `render-notebooks`.

<input type="checkbox"> Click on the dropdown arrow where it says `Run R analysis example` to see what code was run.
